# Generated by Django 6.0.5 on 2026-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('php', 'PHP'), ('typescript', 'TypeScript'), ('java', 'Java'), ('go', 'Go'), ('rust', 'Rust'), ('sql', 'SQL'), ('bash', 'Bash'), ('other', 'Other')], default='python', max_length=50)),
                ('content', models.TextField()),
                ('task_mode', models.CharField(choices=[('explain', 'Explain Code'), ('test', 'Write Tests'), ('docstring', 'Generate Docstrings'), ('review', 'Code Review'), ('chat', 'Chat'), ('pr_review', 'PR Review')], default='chat', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
