# Generated by Django 6.0.5 on 2026-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='source_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
